"""
MCP server for Kore.ai Agentic App Platform.

Exposes the Kore.ai Agentic App Platform as an MCP (Model Context Protocol) server,
enabling Claude Code and other MCP clients to interact with deployed agentic agents
via a structured set of tools.

Usage::

    # From the command line
    agxr-mcp --profile my-profile

    # Or with environment variables (KOREAI_API_KEY, KOREAI_APP_ID, etc.)
    agxr-mcp

    # Adding to Claude Code settings.json
    {
      "mcpServers": {
        "agxr": {
          "command": "uv",
          "args": ["run", "agxr-mcp", "--profile", "my-profile"],
          "cwd": "/path/to/agentic-app-cli"
        }
      }
    }
"""

import argparse
import uuid
from typing import Any, Optional

from fastmcp import FastMCP

from agxr.client import AgenticAPIClient
from agxr.config import Config
from agxr.exceptions import (
    AgenticAPIError,
    AuthenticationError,
    ConfigurationError,
    RunNotFoundError,
)
from agxr.profiles import ProfileManager


class AgentSession:
    """
    Holds MCP-level state for a single conversation session.

    Stores the Kore.ai session references returned by the Sessions API alongside
    a local conversation history. The ``mcp_session_id`` is the stable key returned
    to MCP callers; the ``session_reference`` is the value passed to the Kore.ai API
    in subsequent ``execute_run`` calls.

    Attributes:
        mcp_session_id: Stable identifier returned to and used by MCP tool callers.
        session_reference: Kore.ai ``sessionReference`` assigned by the Sessions API.
            Pass this as ``session_identity`` in ``execute_run`` calls.
        session_id: Kore.ai internal ``sessionId``.
        user_reference: User reference used when creating the session.
        history: Ordered list of ``{"role": "user"|"agent", "text": "..."}`` dicts.
    """

    def __init__(
        self,
        mcp_session_id: str,
        session_reference: str,
        session_id: str,
        user_reference: str,
    ) -> None:
        """
        Initialize session state from Kore.ai Sessions API response data.

        Args:
            mcp_session_id: Stable identifier generated by the MCP server.
            session_reference: API-assigned ``sessionReference`` for this session.
            session_id: API-assigned internal ``sessionId``.
            user_reference: User reference passed to the Sessions API.
        """
        self.mcp_session_id = mcp_session_id
        self.session_reference = session_reference
        self.session_id = session_id
        self.user_reference = user_reference
        self.history: list[dict[str, str]] = []

    def add_turn(self, user_text: str, agent_text: str) -> None:
        """
        Append a user/agent exchange to the conversation history.

        Args:
            user_text: The user's message text.
            agent_text: The agent's response text.
        """
        self.history.append({"role": "user", "text": user_text})
        self.history.append({"role": "agent", "text": agent_text})

    def reset(self) -> None:
        """
        Clear local conversation history.

        This only resets the local history tracked by this session object.
        To also reset the server-side agent memory, use ``end_session`` followed
        by ``start_session`` instead.
        """
        self.history.clear()

    def __repr__(self) -> str:
        return (
            f"AgentSession(mcp_session_id='{self.mcp_session_id}', "
            f"session_reference='{self.session_reference}', "
            f"turns={len(self.history) // 2})"
        )


class AgenticMCPServer:
    """
    FastMCP server exposing the Kore.ai Agentic App Platform as MCP tools.

    Manages multiple concurrent conversation sessions and provides 9 MCP tools
    for interacting with a deployed agentic agent. All tools return structured
    dicts — including structured error responses — rather than raising exceptions,
    so MCP clients receive actionable information.

    Session lifecycle:
        1. Call ``start_session`` to create a Kore.ai session and get an ``mcp_session_id``.
        2. Call ``send_message`` with that ``mcp_session_id`` to chat.
        3. Call ``end_session`` when done to free server-side memory.

    Alternatively, use ``execute_query`` for one-shot queries without session management.

    Attributes:
        mcp: The underlying FastMCP instance.
    """

    def __init__(
        self,
        profile: Optional[str] = None,
        server_name: str = "Kore.ai Agentic App",
    ) -> None:
        """
        Initialize the MCP server with a configured API client.

        Args:
            profile: Name of a configuration profile from ``~/.kore/profiles``.
                If ``None``, credentials are loaded from environment variables
                (KOREAI_API_KEY, KOREAI_APP_ID, KOREAI_ENV_NAME, etc.).
            server_name: Display name for the MCP server. Shown in MCP client UIs.

        Raises:
            ConfigurationError: If required credentials (API key, app ID) are missing.
        """
        self._config = Config(profile=profile)
        self._config.validate()
        self._client = AgenticAPIClient(self._config)
        self._sessions: dict[str, AgentSession] = {}
        self.mcp = FastMCP(server_name)
        self._register_tools()

    def _register_tools(self) -> None:
        """Register all MCP tools with the FastMCP instance."""
        for fn in [
            self.get_server_info,
            self.list_profiles,
            self.start_session,
            self.end_session,
            self.send_message,
            self.get_session_history,
            self.reset_session,
            self.execute_query,
            self.check_run_status,
        ]:
            self.mcp.tool()(fn)

    def run(self, transport: str = "stdio") -> None:
        """
        Start the MCP server.

        Args:
            transport: MCP transport protocol. Currently only ``"stdio"`` is supported,
                which is the standard transport for Claude Code integration.
        """
        self.mcp.run(transport=transport)

    # -------------------------------------------------------------------------
    # Private helpers
    # -------------------------------------------------------------------------

    def _get_session(self, mcp_session_id: str) -> Optional[AgentSession]:
        """Return the AgentSession for the given ID, or None if not found."""
        return self._sessions.get(mcp_session_id)

    def _session_not_found_error(self, mcp_session_id: str) -> dict[str, Any]:
        """Return a structured error dict for an unknown session ID."""
        return {
            "status": "error",
            "error_type": "session_not_found",
            "error": (
                f"No session with id '{mcp_session_id}'. "
                "Call start_session first to create a session."
            ),
        }

    @staticmethod
    def _extract_text(response: dict[str, Any]) -> str:
        """
        Extract and concatenate text content from an API response output array.

        Args:
            response: API response dict containing an ``output`` list.

        Returns:
            Concatenated text from all ``type: "text"`` output items,
            joined with newlines. Returns an empty string if no text items exist.
        """
        return "\n".join(
            item.get("content", "")
            for item in response.get("output", [])
            if item.get("type") == "text" and item.get("content")
        )

    @staticmethod
    def _error_response(error: Exception) -> dict[str, Any]:
        """Map an exception to a structured error response dict."""
        if isinstance(error, AuthenticationError):
            error_type = "authentication"
        elif isinstance(error, ConfigurationError):
            error_type = "configuration"
        elif isinstance(error, RunNotFoundError):
            error_type = "not_found"
        elif isinstance(error, AgenticAPIError):
            error_type = "api_error"
        else:
            error_type = "unexpected"
        return {"status": "error", "error_type": error_type, "error": str(error)}

    # -------------------------------------------------------------------------
    # MCP Tools
    # -------------------------------------------------------------------------

    def get_server_info(self) -> dict[str, Any]:
        """
        Return configuration details for this MCP server.

        Useful for verifying the server is connected to the correct Kore.ai
        application before starting sessions or sending queries.

        Returns:
            Dict with keys:
                - app_id: The configured Kore.ai application identifier.
                - env_name: The target environment (e.g. "production").
                - base_url: The Kore.ai API base URL.
                - active_sessions: Number of currently open sessions.
        """
        return {
            "app_id": self._config.app_id,
            "env_name": self._config.env_name,
            "base_url": self._config.base_url,
            "active_sessions": len(self._sessions),
        }

    def list_profiles(self) -> dict[str, Any]:
        """
        List all available configuration profiles stored in ~/.kore/profiles.

        Returns:
            Dict with keys:
                - profiles: Alphabetically sorted list of profile names.
                - count: Number of profiles available.
        """
        try:
            pm = ProfileManager()
            profiles = pm.list_profiles()
            return {"profiles": profiles, "count": len(profiles)}
        except Exception as e:
            return self._error_response(e)

    def start_session(self, user_reference: Optional[str] = None) -> dict[str, Any]:
        """
        Create a new conversation session with the agent.

        Calls the Kore.ai Sessions API to establish a server-side session and
        returns an mcp_session_id for use with subsequent send_message calls.

        Args:
            user_reference: Optional stable user identifier (e.g. "user-alice").
                If not provided, a unique identifier is auto-generated.

        Returns:
            Dict with keys on success:
                - status: "success"
                - mcp_session_id: Use this ID in subsequent tool calls.
                - session_reference: Kore.ai session reference (informational).
                - user_reference: The user reference used for this session.
            Dict with keys on error:
                - status: "error"
                - error_type: Category of error (e.g. "authentication").
                - error: Human-readable error message.
        """
        try:
            user_ref = user_reference or f"mcp-user-{uuid.uuid4()}"
            session_data = self._client.create_session(user_ref)

            mcp_session_id = f"mcp-{uuid.uuid4()}"
            session = AgentSession(
                mcp_session_id=mcp_session_id,
                session_reference=session_data["sessionReference"],
                session_id=session_data.get("sessionId", ""),
                user_reference=user_ref,
            )
            self._sessions[mcp_session_id] = session

            return {
                "status": "success",
                "mcp_session_id": mcp_session_id,
                "session_reference": session_data["sessionReference"],
                "user_reference": user_ref,
            }
        except Exception as e:
            return self._error_response(e)

    def end_session(self, mcp_session_id: str) -> dict[str, Any]:
        """
        Terminate a session and delete server-side agent memory.

        Args:
            mcp_session_id: The session identifier returned by start_session.

        Returns:
            Dict with keys on success:
                - status: "terminated"
                - mcp_session_id: The terminated session ID.
            Dict with keys on error:
                - status: "error"
                - error_type: Category of error.
                - error: Human-readable error message.
        """
        session = self._get_session(mcp_session_id)
        if session is None:
            return self._session_not_found_error(mcp_session_id)

        try:
            self._client.terminate_session(session.session_reference)
            del self._sessions[mcp_session_id]
            return {"status": "terminated", "mcp_session_id": mcp_session_id}
        except Exception as e:
            return self._error_response(e)

    def send_message(
        self,
        mcp_session_id: str,
        message: str,
    ) -> dict[str, Any]:
        """
        Send a message to the agent in an existing session and return the response.

        Maintains conversation context: the agent remembers prior turns within
        the same session. Use start_session to create a session first.

        Args:
            mcp_session_id: The session identifier returned by start_session.
            message: The user message to send to the agent.

        Returns:
            Dict with keys on success:
                - status: "success"
                - response: The agent's text response.
                - mcp_session_id: Echo of the session ID.
                - turn_count: Total number of complete turns (user+agent) so far.
            Dict with keys on error:
                - status: "error"
                - error_type: Category of error.
                - error: Human-readable error message.
        """
        session = self._get_session(mcp_session_id)
        if session is None:
            return self._session_not_found_error(mcp_session_id)

        try:
            response = self._client.execute_run(
                query=message,
                session_identity=session.session_reference,
                user_reference=session.user_reference,
            )
            text = self._extract_text(response)
            session.add_turn(message, text)

            return {
                "status": "success",
                "response": text,
                "mcp_session_id": mcp_session_id,
                "turn_count": len(session.history) // 2,
            }
        except Exception as e:
            return self._error_response(e)

    def get_session_history(self, mcp_session_id: str) -> dict[str, Any]:
        """
        Return the full conversation history for a session.

        Args:
            mcp_session_id: The session identifier returned by start_session.

        Returns:
            Dict with keys on success:
                - mcp_session_id: Echo of the session ID.
                - history: List of {"role": "user"|"agent", "text": "..."} dicts.
                - turn_count: Number of complete user+agent exchanges.
            Dict with keys on error:
                - status: "error"
                - error_type: Category of error.
                - error: Human-readable error message.
        """
        session = self._get_session(mcp_session_id)
        if session is None:
            return self._session_not_found_error(mcp_session_id)

        return {
            "mcp_session_id": mcp_session_id,
            "history": list(session.history),
            "turn_count": len(session.history) // 2,
        }

    def reset_session(self, mcp_session_id: str) -> dict[str, Any]:
        """
        Clear the local conversation history for a session.

        This resets only the locally tracked history. The Kore.ai server-side
        session remains active and the agent retains its server-side memory.
        To fully reset agent memory, use end_session followed by start_session.

        Args:
            mcp_session_id: The session identifier returned by start_session.

        Returns:
            Dict with keys on success:
                - status: "reset"
                - mcp_session_id: Echo of the session ID.
            Dict with keys on error:
                - status: "error"
                - error_type: Category of error.
                - error: Human-readable error message.
        """
        session = self._get_session(mcp_session_id)
        if session is None:
            return self._session_not_found_error(mcp_session_id)

        session.reset()
        return {"status": "reset", "mcp_session_id": mcp_session_id}

    def execute_query(
        self,
        query: str,
        user_reference: Optional[str] = None,
    ) -> dict[str, Any]:
        """
        Send a one-shot query to the agent without creating a persistent session.

        Unlike send_message, this tool does not maintain conversation history or
        session state. Use it for stateless, single-turn interactions.

        Args:
            query: The query text to send to the agent.
            user_reference: Optional user identifier. Auto-generated if not provided.

        Returns:
            Dict with keys on success:
                - status: "success"
                - response: The agent's text response.
                - run_id: The Kore.ai run identifier (may be None for sync responses).
            Dict with keys on error:
                - status: "error"
                - error_type: Category of error.
                - error: Human-readable error message.
        """
        try:
            user_ref = user_reference or f"mcp-query-{uuid.uuid4()}"
            response = self._client.execute_run(
                query=query,
                session_identity=f"mcp-adhoc-{uuid.uuid4()}",
                user_reference=user_ref,
            )
            text = self._extract_text(response)
            run_id = response.get("sessionInfo", {}).get("runId")

            return {
                "status": "success",
                "response": text,
                "run_id": run_id,
            }
        except Exception as e:
            return self._error_response(e)

    def check_run_status(self, run_id: str) -> dict[str, Any]:
        """
        Check the status of an asynchronous agent run.

        Use this to poll the result of an async run when ``is_async=True`` was used.

        Args:
            run_id: The run identifier (e.g. from sessionInfo.runId in a prior response).

        Returns:
            Dict with keys on success:
                - status: Run status ("pending", "running", "success", or "failed").
                - run_id: Echo of the run identifier.
                - output: List of output items from the run (when status is "success").
            Dict with keys on error:
                - status: "error"
                - error_type: Category of error (e.g. "not_found" for unknown run IDs).
                - error: Human-readable error message.
        """
        try:
            result = self._client.get_run_status(run_id)
            run_data = result.get("run", {})
            output = run_data.get("kwargs", {}).get("output", [])
            status = run_data.get("status", result.get("status", "unknown"))

            return {
                "status": status,
                "run_id": run_id,
                "output": output,
            }
        except Exception as e:
            return self._error_response(e)


def main() -> None:
    """
    Entry point for the agxr-mcp command.

    Parses command-line arguments and starts the MCP server over stdio transport.
    """
    parser = argparse.ArgumentParser(
        prog="agxr-mcp",
        description="Kore.ai Agentic App MCP Server — exposes agent interactions as MCP tools",
    )
    parser.add_argument(
        "--profile",
        default=None,
        metavar="NAME",
        help="Configuration profile from ~/.kore/profiles. "
             "If omitted, uses KOREAI_* environment variables.",
    )
    parser.add_argument(
        "--transport",
        default="stdio",
        choices=["stdio"],
        help="MCP transport protocol (default: stdio).",
    )
    args = parser.parse_args()

    server = AgenticMCPServer(profile=args.profile)
    server.run(transport=args.transport)


if __name__ == "__main__":
    main()
